### ISSUE TITLE
Speed up CI

### ISSUE THREAD

**Issue by deemp** [nix-community/nix-vscode-extensions#72]
## Details

Currently, we get the new hash for a cache every time the action runs because we always update the `flake.lock` in the `template` directory.

https://github.com/nix-community/nix-vscode-extensions/actions/runs/10518229237/job/29143682905#step:4:22

## Subtasks

- [ ] Don't use `template/flake.lock` in the main job
- [ ] Have `saveFlakes` not save the cache for the `template` directory.
- [ ] Have a separate function for saving the flake in the `template` directory.

**Comment by deemp** [comment]
These improvements are implemented (https://github.com/nix-community/nix-vscode-extensions/blob/401328473735d2802454d5521451c0e13d94903d/.github/workflows/ci.yaml).
